# Generated by Django 3.2.18 on 2023-05-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_online', models.BooleanField(default=True)),
                ('available_for_pickup', models.BooleanField(default=True)),
                ('available_electronically', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('track_inventory', models.BooleanField(default=True)),
                ('inventory_alert_type', models.CharField(blank=True, max_length=255)),
                ('inventory_alert_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('product_data', models.TextField(blank=True)),
            ],
        ),
    ]
